[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.5"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "^1.11.3"

[prune]
  go-tests = true
  unused-packages = true
